-- Seed content transcribed from matcha.docx.
-- Important: numeric tasting scores, brewing ratios and reference prices are intentionally NULL
-- because the source document does not provide those values.

insert into public.tea_brands
(id, slug, name, japanese_name, description_vi, description_en, origin_country, origin_region, logo_url, is_visible, sort_order)
values
('brand-marukyu-koyamaen','marukyu-koyamaen','MARUKYU KOYAMAEN','丸久小山園',$$Marukyu Koyamaen (丸久小山園) là một trong những thương hiệu sản xuất trà xanh và matcha lâu đời, uy tín bậc nhất Nhật Bản, có trụ sở tại vùng Uji, Kyoto — thủ phủ matcha nổi tiếng thế giới.$$ ,null,'Japan','Uji, Kyoto','/images/brands/marukyu-koyamaen.png',true,1),
('brand-ishimoto','ishimoto','ISHIMOTO','石本川口園',$$Nhà trà Ishimoto Kawaguchien (石本川口園) đến từ vùng trà danh tiếng Uji (Kyoto) / Osaka của Nhật Bản. Thương hiệu này tập trung vào dòng Matcha (bột trà xanh) với các cấp độ từ dùng hằng ngày đến phục vụ nghi thức trà đạo cao cấp.$$ ,null,'Japan','Uji (Kyoto) / Osaka',null,true,2),
('brand-shogyokuen','shogyokuen','SHOGYOKUEN','祥玉園製茶',$$Shogyokuen (祥玉園製茶) là một thương hiệu trà đạo và nhà sản xuất trà Uji lâu đời, danh tiếng hàng đầu tại vùng Uji/Kyotanabe, tỉnh Kyoto, Nhật Bản.$$ ,null,'Japan','Uji/Kyotanabe, Kyoto','/images/brands/shogyokuen.png',true,3),
('brand-atami-tea-store','atami-tea-store','ATAMI TEA STORE','熱海青葉舎',$$ATAMI TEA STORE (thường được biết đến với tên gọi thương hiệu trà Atami Seiyousha - 熱海青葉舎) là thương hiệu / quán trà chuyên về Matcha và các dòng trà Nhật Bản cao cấp.$$ ,null,'Japan',null,null,true,4),
('brand-waba-tea','waba-tea','WABA TEA',null,$$Waba Tea là thương hiệu chuyên cung cấp các dòng bột trà xanh matcha, houjicha và sencha chất lượng cao được tuyển chọn và nhập khẩu trực tiếp từ Nhật Bản (các vùng trà nổi tiếng như Kagoshima, Yame, Uji).$$ ,null,'Japan','Kagoshima / Yame / Uji (brand sourcing regions)','/images/brands/waba-tea.jpg',true,5)
on conflict (id) do update set
slug=excluded.slug,name=excluded.name,japanese_name=excluded.japanese_name,description_vi=excluded.description_vi,origin_country=excluded.origin_country,origin_region=excluded.origin_region,logo_url=excluded.logo_url,is_visible=excluded.is_visible,sort_order=excluded.sort_order;

insert into public.tea_products
(id,slug,name,japanese_name,brand_id,tea_type,origin_country,origin_region,tasting_summary_vi,tasting_summary_en,aroma,finish,tasting_notes,recommended_for,body_score,umami_score,sweetness_score,bitterness_score,creaminess_score,brewing_matcha_grams,brewing_water_ml,brewing_temperature,brewing_time,price,price_unit,price_note,is_featured,is_visible,sort_order,image_url,gallery,source_page)
values
('tea-isuzu','isuzu','Isuzu','五十鈴','brand-marukyu-koyamaen','matcha','Japan',null,$$Hương hoa thoang thoảng, chát nhẹ, đắng nhẹ, hậu béo ngọt dịu.$$,$$light body, light floral aroma, low bitterness and a soft sweet finish$$,$$Hương hoa thoang thoảng$$,$$hậu béo ngọt dịu$$,array['Floral','Light body','Low bitterness','Soft sweet finish'],array[]::text[],null,null,null,null,null,null,null,null,null,null,null,null,true,true,1,'/images/tea/marukyu/isuzu.jpg',array[]::text[],1),
('tea-chigi-no-shiro','chigi-no-shiro','Chigi no Shiro','千代の白','brand-marukyu-koyamaen','matcha','Japan',null,$$Đậm trà trung bình, mặn nhẹ, umami đơn giản, béo, hậu ngọt.$$,$$medium body, subtie saltiness, simple umami, creamy, grassy sweet aftertaste$$,null,$$hậu ngọt$$,array['Medium body','Subtle saltiness','Simple umami','Creamy','Grassy sweet aftertaste'],array[]::text[],null,null,null,null,null,null,null,null,null,null,null,null,false,true,2,'/images/tea/marukyu/chigi-no-shiro.jpg',array[]::text[],1),
('tea-yugen','yugen','Yugen','又玄','brand-marukyu-koyamaen','matcha','Japan',null,$$Vị đậm đà vừa phải, đậu hà lan luộc béo bùi, umami trung bình, đắng nhẹ, hậu ngọt.$$,$$light tea body, bolied bean nuttiness, medium umami, low bitterbess and soft sweet finish$$,$$đậu hà lan luộc béo bùi$$,$$hậu ngọt$$,array['Boiled bean','Nutty','Medium umami','Low bitterness','Soft sweet finish'],array[]::text[],null,null,null,null,null,null,null,null,null,null,null,null,true,true,3,'/images/tea/marukyu/yugen.jpg',array[]::text[],1),
('tea-wako-marukyu','wako-marukyu-koyamaen','Wako','和光','brand-marukyu-koyamaen','matcha','Japan',null,$$Umami đậm và dày, hương hoa cỏ phong phú, thoáng chocolate đen, béo, hậu vị sâu.$$,$$Rich and thick umami, layered vegetal notes, hint of dark chocolate, creamy, deep lingering finish$$,$$hương hoa cỏ phong phú, thoáng chocolate đen$$,$$hậu vị sâu$$,array['Rich umami','Vegetal','Dark chocolate','Creamy','Deep finish'],array[]::text[],null,null,null,null,null,null,null,null,null,null,null,null,true,true,4,'/images/tea/marukyu/wako.jpg',array[]::text[],1),
('tea-kinrin','kinrin','Kinrin','金輪','brand-marukyu-koyamaen','matcha','Japan',null,$$Umami dày, ngọt cỏ, chuối nướng, béo bùi, sánh mịn, hậu vị đậm trà.$$,$$Thick umami, grassy sweetnes, roasted banana, nutty-creamy, strong tea finish$$,$$ngọt cỏ, chuối nướng$$,$$hậu vị đậm trà$$,array['Thick umami','Grassy sweetness','Roasted banana','Nutty-creamy','Strong tea finish'],array[]::text[],null,null,null,null,null,null,null,null,null,null,null,null,false,true,5,'/images/tea/marukyu/kinrin.jpg',array[]::text[],2),
('tea-unkaku','unkaku','Unkaku','雲鶴','brand-marukyu-koyamaen','matcha','Japan',null,$$Body dày, đậm trà, thơm hoa, béo bùi, umami phức tạp, hậu ngọt ấn tượng.$$,$$dense body, bold tea, floral aroma, nutty creamy, complex umami, reamarkable sweet finish$$,$$thơm hoa$$,$$hậu ngọt ấn tượng$$,array['Dense body','Bold tea','Floral','Nutty creamy','Complex umami','Sweet finish'],array[]::text[],null,null,null,null,null,null,null,null,null,null,null,null,true,true,6,'/images/tea/marukyu/unkaku.jpg',array[]::text[],2),
('tea-wako-ishimoto','wako-ishimoto','Wako','和光','brand-ishimoto','matcha','Japan',null,$$Hương trái cây, hoa trắng, vanilla, hậu ngọt, béo, nutty đậm đà, umami dày.$$,$$fruity and floral notes, sweet finish, rich nutty and thick umami$$,$$Hương trái cây, hoa trắng, vanilla$$,$$hậu ngọt$$,array['Fruity','White floral','Vanilla','Rich nutty','Thick umami','Sweet finish'],array[]::text[],null,null,null,null,null,null,null,null,null,null,null,null,true,true,7,'/images/tea/wako-ishimoto.svg',array[]::text[],2),
('tea-nishiki','nishiki','Nishiki','錦','brand-ishimoto','matcha','Japan',null,$$Thơm bùi béo hạnh nhân, hạt phỉ lẫn hương hoa trắng tinh tế, béo ngậy, đậm trà, umami dày.$$,$$aromatic almond and hazelnut notes layered with delicate white florals, thick umami and creamy sweet finish$$,$$hạnh nhân, hạt phỉ, hoa trắng$$,$$creamy sweet finish$$,array['Almond','Hazelnut','White floral','Thick umami','Creamy sweet finish'],array[]::text[],null,null,null,null,null,null,null,null,null,null,null,null,false,true,8,'/images/tea/nishiki.svg',array[]::text[],2),
('tea-izumi-no-shiro','izumi-no-shiro','Izumi no Shiro','泉の白','brand-shogyokuen','matcha','Japan',null,$$Vị trà nhẹ, đậu trắng luộc, béo bùi, chát và đắng tinh tế, umami trung bình.$$,$$light bodied matcha with white bean notes, gentle nuttiness, refined bitterness, and balanced umami$$,$$đậu trắng luộc$$,null,array['Light body','White bean','Gentle nuttiness','Refined bitterness','Balanced umami'],array[]::text[],null,null,null,null,null,null,null,null,null,null,null,null,true,true,9,'/images/tea/izumi-no-shiro.svg',array[]::text[],3),
('tea-seiyousha','seiyousha','Seiyousha',null,'brand-atami-tea-store','matcha','Japan',null,$$Hương đậu nành, hạnh nhân rang, nốt hương cacao thoảng, berry và floral nhẹ, béo bùi cân bằng tốt, hậu ngọt mượt, gần như không đắng chát.$$,$$nutty notes of roasted soybeans and almond, with hints of cacao, berries and florals, smooth, sweet finish with little to no bitterness$$,$$đậu nành, hạnh nhân rang, cacao, berry, floral nhẹ$$,$$hậu ngọt mượt$$,array['Roasted soybean','Almond','Cacao','Berry','Floral','Smooth sweet finish'],array[]::text[],null,null,null,null,null,null,null,null,null,null,null,null,true,true,10,'/images/tea/seiyousha.svg',array[]::text[],3),
('tea-hojicha-type-a','hojicha-type-a-marukyu-koyamaen','Hojicha type A','焙じ茶','brand-marukyu-koyamaen','hojicha','Japan',null,$$Hương trà nhẹ, không đắng chát, tựa trà sữa gạo rang, ít caffeine$$,$$Light tea aroma, smooth and mellow, reminiscent of roasted rice milk tea, with low caffeine$$,$$Hương trà nhẹ$$,$$smooth and mellow$$,array['Light tea aroma','Roasted rice milk tea','Smooth','Low caffeine'],array[]::text[],null,null,null,null,null,null,null,null,null,null,null,null,false,true,11,'/images/tea/hojicha-type-a.svg',array[]::text[],4),
('tea-tsuki','tsuki-mh2','Tsuki (MH2)','月','brand-waba-tea','matcha','Japan',null,$$Dòng trà ôn hòa, hương vị cân bằng, thoảng mùi hoa cỏ nhẹ nhàng.$$ ,null,$$thoảng mùi hoa cỏ nhẹ nhàng$$,null,array['Balanced','Gentle floral'],array[]::text[],null,null,null,null,null,null,null,null,null,null,null,null,false,true,12,'/images/tea/tsuki.svg',array[]::text[],5),
('tea-hana','hana-mh3','Hana (MH3)','花','brand-waba-tea','matcha','Japan',null,$$Béo ngậy (creamy), vị umami ngọt kéo dài, thơm mùi hạt nướng/chocolate nhẹ và ít đắng$$ ,null,$$hạt nướng/chocolate nhẹ$$,$$vị umami ngọt kéo dài$$,array['Creamy','Sweet umami','Roasted nuts','Light chocolate','Low bitterness'],array[]::text[],null,null,null,null,null,null,null,null,null,null,null,null,true,true,13,'/images/tea/hana.svg',array[]::text[],5)
on conflict (id) do update set
slug=excluded.slug,name=excluded.name,japanese_name=excluded.japanese_name,brand_id=excluded.brand_id,tea_type=excluded.tea_type,tasting_summary_vi=excluded.tasting_summary_vi,tasting_summary_en=excluded.tasting_summary_en,aroma=excluded.aroma,finish=excluded.finish,tasting_notes=excluded.tasting_notes,is_featured=excluded.is_featured,is_visible=excluded.is_visible,sort_order=excluded.sort_order,image_url=excluded.image_url,source_page=excluded.source_page;

insert into public.homepage_content (section_key,title,eyebrow,body,payload,is_visible,sort_order)
values ('hero','MATCHA, NOT JUST GREEN.','Japanese tea archive / tasting journal','A quiet study of Japanese matcha.','{}'::jsonb,true,1)
on conflict (section_key) do nothing;
